# Generated by Django 4.2.17 on 2024-12-23 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100, verbose_name='Заявка')),
                ('moderator', models.CharField(max_length=100, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(blank=True, default='Default PC name', max_length=255, null=True, verbose_name='Имя компьютера')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('issue', models.CharField(max_length=255, verbose_name='Название проблемы')),
                ('issue_description', models.CharField(max_length=400, verbose_name='Описание проблемы')),
                ('phone', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='main/images/', verbose_name='Изображение проблемы')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания заявки')),
                ('closing_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время закрытия заявки')),
                ('status', models.CharField(default='Не рассмотрена', max_length=100, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО модератора')),
                ('mail', models.EmailField(max_length=50, unique=True, verbose_name='Почта')),
                ('month_tickets', models.IntegerField(default=0, verbose_name='Количество заявок в месяц')),
            ],
            options={
                'verbose_name': 'Модератор',
                'verbose_name_plural': 'Модераторы',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproblems', to='main.problems')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
    ]
